version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
