// Package catalogdoc renders the registered module catalog as Markdown.
package catalogdoc

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/0xv1n/macnoise/pkg/module"
)

// Render returns the complete module catalog in deterministic Markdown.
func Render(generators []module.Generator) ([]byte, error) {
	entries := make([]module.CatalogEntry, 0, len(generators))
	for _, generator := range generators {
		entries = append(entries, module.NewCatalogEntry(generator))
	}
	sortEntries(entries)

	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by `make generate-catalog`; DO NOT EDIT. -->\n\n")
	buf.WriteString("# Module catalog\n\n")
	buf.WriteString("This reference is generated from the module registry. Use `macnoise info <module>` to inspect one module at the command line, or `macnoise list --format jsonl` for machine-readable catalog entries.\n\n")

	counts := make(map[module.Category]int)
	for _, entry := range entries {
		counts[entry.Category]++
	}
	for _, category := range module.AllCategories() {
		if counts[category] > 0 {
			fmt.Fprintf(&buf, "- [%s](#%s) (%d)\n", category, category, counts[category])
		}
	}

	var current module.Category
	for _, entry := range entries {
		if entry.Category != current {
			current = entry.Category
			fmt.Fprintf(&buf, "\n## %s\n", current)
		}
		if err := renderEntry(&buf, entry); err != nil {
			return nil, fmt.Errorf("render %s: %w", entry.Name, err)
		}
	}

	return buf.Bytes(), nil
}

func sortEntries(entries []module.CatalogEntry) {
	order := make(map[module.Category]int)
	for index, category := range module.AllCategories() {
		order[category] = index
	}
	sort.Slice(entries, func(i, j int) bool {
		left, right := entries[i], entries[j]
		if left.Category != right.Category {
			return order[left.Category] < order[right.Category]
		}
		return left.Name < right.Name
	})
}

func renderEntry(buf *bytes.Buffer, entry module.CatalogEntry) error {
	fmt.Fprintf(buf, "\n### `%s`\n\n%s\n\n", entry.Name, entry.Description)
	buf.WriteString("| Metadata | Value |\n|---|---|\n")
	fmt.Fprintf(buf, "| Privilege | %s |\n", inline(string(entry.Privileges)))
	fmt.Fprintf(buf, "| Minimum macOS | %s |\n", inline(entry.MinMacOS))
	fmt.Fprintf(buf, "| Tags | %s |\n", inlineList(entry.Tags))
	fmt.Fprintf(buf, "| Event types | %s |\n", inlineList(entry.EventTypes))
	fmt.Fprintf(buf, "| ATT&CK | %s |\n", mitreLinks(entry.MITRE))

	if len(entry.Params) > 0 {
		buf.WriteString("\n#### Parameters\n\n")
		buf.WriteString("| Name | Type | Required | Sensitive | Default | Example | Constraints | Description |\n")
		buf.WriteString("|---|---|---|---|---|---|---|---|\n")
		for _, param := range entry.Params {
			defaultValue, err := formatValue(param.Default)
			if err != nil {
				return fmt.Errorf("parameter %s default: %w", param.Name, err)
			}
			example, err := formatValue(param.Example)
			if err != nil {
				return fmt.Errorf("parameter %s example: %w", param.Name, err)
			}
			fmt.Fprintf(buf, "| %s | %s | %s | %s | %s | %s | %s | %s |\n",
				inline(param.Name), inline(string(param.Type)), yesNo(param.Required), yesNo(param.Sensitive),
				defaultValue, example, constraints(param), cell(param.Description))
		}
	}

	if len(entry.Outputs) > 0 {
		buf.WriteString("\n#### Outputs\n\n")
		buf.WriteString("| Name | Type | Sensitive | Description |\n|---|---|---|---|\n")
		for _, output := range entry.Outputs {
			fmt.Fprintf(buf, "| %s | %s | %s | %s |\n", inline(output.Name), inline(string(output.Type)), yesNo(output.Sensitive), cell(output.Description))
		}
	}
	return nil
}

func formatValue(value any) (string, error) {
	if value == nil {
		return "-", nil
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return inline(string(encoded)), nil
}

func constraints(param module.CatalogParam) string {
	var values []string
	if param.Range != nil {
		if param.Range.Max == 0 {
			values = append(values, fmt.Sprintf("min %d", param.Range.Min))
		} else {
			values = append(values, fmt.Sprintf("%d-%d", param.Range.Min, param.Range.Max))
		}
	}
	if len(param.Choices) > 0 {
		values = append(values, "one of "+inlineList(param.Choices))
	}
	if len(values) == 0 {
		return "-"
	}
	return strings.Join(values, "; ")
}

func mitreLinks(mappings []module.CatalogMITRE) string {
	if len(mappings) == 0 {
		return "-"
	}
	values := make([]string, 0, len(mappings))
	for _, mapping := range mappings {
		id := mapping.Technique
		url := "https://attack.mitre.org/techniques/" + mapping.Technique + "/"
		if mapping.SubTechnique != "" {
			id = mapping.SubTechnique
			parts := strings.SplitN(mapping.SubTechnique, ".", 2)
			if len(parts) == 2 {
				url += parts[1] + "/"
			}
		}
		values = append(values, fmt.Sprintf("[%s](%s) %s", id, url, cell(mapping.Name)))
	}
	return strings.Join(values, "<br>")
}

func inlineList(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = inline(value)
	}
	return strings.Join(quoted, ", ")
}

func inline(value string) string {
	if value == "" {
		return "-"
	}
	value = cell(value)
	if strings.Contains(value, "`") {
		return "``" + value + "``"
	}
	return "`" + value + "`"
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func cell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.ReplaceAll(value, "\n", "<br>")
}
